app.exception.ioexception.message="Error durante el proceso de validaci√≥n de ADN"
